[package]
name = "rendy-shader"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]
edition = "2018"
repository = "https://github.com/omni-viral/rendy"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/rendy-shader"
keywords = ["graphics", "gfx-hal", "rendy"]
categories = ["rendering"]
description = "Rendy's shader compilation tool"

[dependencies]
failure = "0.1"
gfx-hal = {git = "https://github.com/gfx-rs/gfx", rev = "5b84957d47592969507fb9e9b69810af13098819"}
rendy-factory = { version = "0.1", path = "../factory" }
shaderc = { version = "0.3", optional = true }
serde = { version = "1.0", optional = true, features = ["derive"] }
serde_bytes = { version = "0.10.5", optional = true }

[features]
shader-compiler = ["shaderc"]
serde-1 = ["serde", "serde_bytes"]
