[package]
name = "rendy-command"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]
edition = "2018"
repository = "https://github.com/omni-viral/rendy"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/rendy-command"
keywords = ["graphics", "gfx-hal", "rendy"]
categories = ["rendering"]
description = "Rendy's queues and commands tools"

[features]
no-slow-safety-checks = ["rendy-util/no-slow-safety-checks"]

[dependencies]
gfx-hal = { git = "https://github.com/gfx-rs/gfx", rev = "5b84957d47592969507fb9e9b69810af13098819" }
derivative = "1.0"
failure = "0.1"
relevant = { version = "0.4", features = ["log", "backtrace"] }
smallvec = "0.6"
rendy-util = { version = "0.1", path = "../util" }